update files pulled via gget

diff --git a/.github/workflows/gget-update.yml b/.github/workflows/gget-update.yml
--- a/.github/workflows/gget-update.yml
+++ b/.github/workflows/gget-update.yml
@@ -1,10 +1,10 @@
 #
 #    __                          __
-#   / /____ ___ ____  ___  ___ _/ /       This script is provided to you by https://github.com/tegonal/github-commons
-#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        It is licensed under Creative Commons Zero v1.0 Universal
+#   / /____ ___ ____  ___  ___ _/ /       This script is provided to you by https://github.com/tegonal/gget
+#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        It is licensed under Apache 2.0
 #  \__/\__/\_, /\___/_//_/\_,_/_/         Please report bugs and contribute back your improvements
 #         /___/
-#                                         Version: v0.5.0-SNAPSHOT
+#                                         Version: v0.9.0
 #
 ###################################
 name: "gget update"
@@ -14,6 +14,7 @@ on:
   push:
     branches:
       - do-gget-update
+  workflow_dispatch:
 
 jobs:
   Update:
@@ -26,7 +27,7 @@ jobs:
       - name: Install gget
         run: |
           set -e
-          # see install.doc.sh in root of this project, MODIFY THERE NOT HERE
+          # see install.doc.sh in https://github.com/tegonal/gget, MODIFY THERE NOT HERE (please report bugs)
           currentDir=$(pwd) && \
           tmpDir=$(mktemp -d -t gget-download-install-XXXXXXXXXX) && cd "$tmpDir" && \
           wget "https://raw.githubusercontent.com/tegonal/gget/main/.gget/signing-key.public.asc" && \
@@ -39,22 +40,24 @@ jobs:
           wget "https://raw.githubusercontent.com/tegonal/gget/main/install.sh.sig" && \
           gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
           chmod +x ./install.sh && \
-          echo "verification successful" && verificationResult=true || (echo "verification failed, don't continue"; exit 1) && \
-          ./install.sh && \
-          false || cd "$currentDir" && rm -r "$tmpDir" && "${verificationResult:-false}"
+          echo "verification successful" || (echo "verification failed, don't continue"; exit 1) && \
+          ./install.sh && result=true || (echo "installation failed"; exit 1) && \
+          false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
       - name: reset gpg keys
         run: gget reset --gpg-only true
       - name: gget update
         run: gget update
+      - name: git status
+        run: git status
       - name: Create pull request if necessary
         uses: peter-evans/create-pull-request@v4
         with:
-          branch: gget-update
+          branch: gget/update
           base: main
-          title: Updates via gget
+          title: Changes via gget update
           commit-message: update files pulled via gget
-          body: "following the changes after running: gget update"
+          body: "following the changes after running `gget update` (among other things)"
           delete-branch: true
           token: ${{ secrets.AUTO_PR_TOKEN }}
           push-to-fork: ${{ secrets.AUTO_PR_FORK_NAME }}
